In [1]:
"""
Simple TensorFlow exercises
You should thoroughly test your code
"""

import tensorflow as tf
import pandas as pd
from sklearn.cross_validation import train_test_split

/home/jesse/anaconda3/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


# Problem1: Ops exercises

In [31]:
###############################################################################
# 1a: Create two random 0-d tensors x and y of any distribution.
# Create a TensorFlow object that returns x + y if x < y, and x - y otherwise.
# Hint: look up tf.cond()
# I do the first problem for you
###############################################################################

x = tf.random_uniform([])  # Empty array as shape creates a scalar.
y = tf.random_uniform([])
out = tf.cond(tf.less(x, y), lambda: tf.add(x, y), lambda: tf.subtract(x, y))
with tf.Session() as sess:
    x, y, result = sess.run([x, y, out])
    print("x: ",x)
    print("y: ", y)
    print("1a result: ", result)
    print()

###############################################################################
# 1b: Create two 0-d tensors x and y randomly selected from -1 and 1.
# Return x + y if x < y, x - y if x > y, 0 otherwise.
# Hint: Look up tf.case().
###############################################################################

x = tf.random_uniform([], -1, 1, dtype=tf.float32)
y = tf.random_uniform([], -1, 1, dtype=tf.float32)

def f1(): return tf.add(x, y)
def f2(): return tf.subtract(x, y)
def f3(): return tf.constant(0.0)

out = tf.case({tf.less(x, y): f1, tf.greater(x, y): f2}, default=f3, exclusive=True)
with tf.Session() as sess:
    x, y, result = sess.run([x, y, out])
    print("x: ",x)
    print("y: ", y)
    print("1b result: ", result)
    print()

###############################################################################
# 1c: Create the tensor x of the value [[0, -2, -1], [0, 1, 2]] 
# and y as a tensor of zeros with the same shape as x.
# Return a boolean tensor that yields Trues if x equals y element-wise.
# Hint: Look up tf.equal().
###############################################################################

x = tf.constant([[0, -2, -1], [0, 1, 2]])
y = tf.zeros_like(x)
out = tf.equal(x, y)

with tf.Session() as sess:
    x, y, result = sess.run([x, y, out])
    print("x: ", x)
    print("y: ", y)
    print("1c result: ", result)
    print()
    
###############################################################################
# 1d: Create the tensor x of value 
# [29.05088806,  27.61298943,  31.19073486,  29.35532951,
#  30.97266006,  26.67541885,  38.08450317,  20.74983215,
#  34.94445419,  34.45999146,  29.06485367,  36.01657104,
#  27.88236427,  20.56035233,  30.20379066,  29.51215172,
#  33.71149445,  28.59134293,  36.05556488,  28.66994858].
# Get the indices of elements in x whose values are greater than 30.
# Hint: Use tf.where().
# Then extract elements whose values are greater than 30.
# Hint: Use tf.gather().
###############################################################################

x = tf.constant([29.05088806,  27.61298943,  31.19073486,  29.35532951,
                 30.97266006,  26.67541885,  38.08450317,  20.74983215,
                 34.94445419,  34.45999146,  29.06485367,  36.01657104,
                 27.88236427,  20.56035233,  30.20379066,  29.51215172,
                 33.71149445,  28.59134293,  36.05556488,  28.66994858])

indices = tf.where(condition=x>30)
result = tf.gather(params=x, indices=indices)
with tf.Session() as sess:
    indices, result = sess.run([indices, result])
    print("1d indices: ", indices)
    print("1d elements: ", result)
    print()
###############################################################################
# 1e: Create a diagnoal 2-d tensor of size 6 x 6 with the diagonal values of 1,
# 2, ..., 6
# Hint: Use tf.range() and tf.diag().
###############################################################################

out = tf.diag(tf.range(1,7))
with tf.Session() as sess:
    result = sess.run(out)
    print("1e result: ", result)
    print()

###############################################################################
# 1f: Create a random 2-d tensor of size 10 x 10 from any distribution.
# Calculate its determinant.
# Hint: Look at tf.matrix_determinant().
###############################################################################

x = tf.random_normal(shape=(10, 10))
out = tf.matrix_determinant(x)
with tf.Session() as sess:
    matrix, result = sess.run([x, out])
    print("matrix: ", matrix)
    print("1f result: ", result)
    print()
###############################################################################
# 1g: Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9].
# Return the unique elements in x
# Hint: use tf.unique(). Keep in mind that tf.unique() returns a tuple.
###############################################################################

x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
out = tf.unique(x)
with tf.Session() as sess:
    result = sess.run(out)
    print("1g result: ", result)
    print()
###############################################################################
# 1h: Create two tensors x and y of shape 300 from any normal distribution,
# as long as they are from the same distribution.
# Use tf.less() and tf.select() to return:
# - The mean squared error of (x - y) if the average of all elements in (x - y)
#   is negative, or
# - The sum of absolute value of all elements in the tensor (x - y) otherwise.
# Hint: see the Huber loss function in the lecture slides 3.
###############################################################################

x = tf.random_normal([300])
y = tf.random_normal([300])

residual = tf.reduce_mean(x - y)
mse = tf.reduce_mean(tf.square(x - y))
sav = tf.reduce_sum(tf.abs(x - y))
condition = tf.less(residual, 0)
out = tf.cond(condition, lambda: mse, lambda: sav)

with tf.Session() as sess:
    residual, result = sess.run([residual, out])
    print("average of all elements in (x-y)", residual)
    print("1h result: ", result)
    print()

x:  0.0323758
y:  0.353652
1a result:  0.386028

x:  -0.490113
y:  0.124855
1b result:  -0.365258

x:  [[ 0 -2 -1]
 [ 0  1  2]]
y:  [[0 0 0]
 [0 0 0]]
1c result:  [[ True False False]
 [ True False False]]

1d indices:  [[ 2]
 [ 4]
 [ 6]
 [ 8]
 [ 9]
 [11]
 [14]
 [16]
 [18]]
1d elements:  [[ 31.19073486]
 [ 30.97266006]
 [ 38.08450317]
 [ 34.94445419]
 [ 34.45999146]
 [ 36.01657104]
 [ 30.20379066]
 [ 33.71149445]
 [ 36.05556488]]

1e result:  [[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]

matrix:  [[ 0.37541512 -0.1299666  -0.31316665  1.63839245 -0.60459846 -1.35199022
   0.48886666 -1.57846987 -0.69738352 -1.36678708]
 [-1.0150975  -0.23947066  0.21490736  1.44574368 -1.41944253 -0.83826554
  -1.0676074  -0.08227249  0.88546157 -0.45222366]
 [-0.76473379 -0.57149118 -0.25639609 -3.09495282 -1.27446663  0.26178613
   0.45012856 -0.34655464 -1.37166035 -0.0285361 ]
 [-1.40588021 -0.22753894  1.67243361  0.55112636  2.08001351  0.4491986
   0

# Problem2: Logistic regression

In [34]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
import time

In [63]:
# step 1: read in data
print("Loading data......")
MNIST = input_data.read_data_sets("MNIST_data/", one_hot=True)
print("Done!")
# step 2: define parameters for the model
LEARNING_RATE = 1e-2
BATCH_SIZE = 128
N_EPOCHS = 45
H1_UNITS = 512
H2_UNITS = 380
KEEP_PROB = 0.5

# step 3: create placeholders for features and labels
# each image in the MNIST data is of shape 28*28 = 784
# therefore, each image is represented with a 1x784 tensor
# there are 10 classes for each image, corresponding to digits 0 - 9.
# each label is one hot vector.

X = tf.placeholder(tf.float32, [BATCH_SIZE, 784])
Y = tf.placeholder(tf.float32, [BATCH_SIZE, 10])
keep_prob = tf.placeholder(tf.float32)

# step 4: create weights and bias
# w is initialized to random variables with mean of 0, stddev of 0.01
# b is initialized to 0
# shape of w depends on the dimension of X and Y so that Y = tf.matmul(X, w)
# shape of b depends on Y

W1 = tf.Variable(tf.random_normal(shape=[784, H1_UNITS], stddev=0.01), name="W1")
b1 = tf.Variable(tf.zeros([1, H1_UNITS]), name="b1")
h1 = tf.nn.relu(tf.matmul(X, W1)+b1)
h1_drop = tf.nn.dropout(h1, KEEP_PROB)

W2 = tf.Variable(tf.random_normal(shape=[H1_UNITS, H2_UNITS], stddev=0.01), name="W2")
b2 = tf.Variable(tf.zeros([1, H2_UNITS]), name="b2")
h2 = tf.nn.relu(tf.matmul(h1_drop, W2)+b2)

W_out = tf.Variable(tf.random_normal(shape=[H2_UNITS, 10], stddev=0.01), name="W_out")
b_out = tf.Variable(tf.zeros([1, 10]), name="b_out")


# step 5: predict Y from X and w, b
# the model that returns probability distribution of possible label of the image
# through the softmax layer
# a batch_size x 10 tensor that represents the possibility of the digits

logits = tf.matmul(h2, W_out) + b_out

# step 6: define loss function
# use softmax cross entropy with logits as the loss function
# compute mean cross entropy, softmax is applied internally
Y_ = tf.nn.softmax(logits)
cross_entropy_loss = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(Y_), reduction_indices=[1]))

# Step 7: define training op
# using gradient descent with learning rate of 0.01 to minimize cost
optimizer = tf.train.GradientDescentOptimizer(LEARNING_RATE).minimize(cross_entropy_loss)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    n_batches = int(MNIST.train.num_examples/BATCH_SIZE)
    for i in range(N_EPOCHS):
        total_loss = 0.0
        for _ in range(n_batches):
            X_batch, Y_batch = MNIST.train.next_batch(BATCH_SIZE)
            _, loss = sess.run([optimizer, cross_entropy_loss], feed_dict={X:X_batch, Y:Y_batch})
            total_loss += loss
        print("Total loss in iter%d: " % i, total_loss)
    
    # test model
    n_batches = int(MNIST.test.num_examples/BATCH_SIZE)
    total_correct_preds = 0.0
    for i in range(n_batches):
        X_batch, Y_batch = MNIST.test.next_batch(BATCH_SIZE)
        _, loss_batch, pred = sess.run([optimizer, cross_entropy_loss, Y_], feed_dict={X:X_batch, Y:Y_batch})
        correct_preds = tf.equal(tf.argmax(pred,1), tf.argmax(Y_batch,1))
        accuracy = tf.reduce_sum(tf.cast(correct_preds, tf.float32))
        total_correct_preds += sess.run(accuracy)
    print("Accuracy {0}".format(total_correct_preds / MNIST.test.num_examples))

Loading data......
Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Done!
Total loss in iter0:  986.721645832
Total loss in iter1:  983.320941925
Total loss in iter2:  968.140684128
Total loss in iter3:  875.077893853
Total loss in iter4:  582.860703468
Total loss in iter5:  385.174012065
Total loss in iter6:  310.377721101
Total loss in iter7:  263.057091296
Total loss in iter8:  231.716411233
Total loss in iter9:  211.488890141
Total loss in iter10:  196.65275231
Total loss in iter11:  185.013164118
Total loss in iter12:  176.04174915
Total loss in iter13:  167.040936559
Total loss in iter14:  161.032677472
Total loss in iter15:  155.041350782
Total loss in iter16:  149.426403373
Total loss in iter17:  144.199834034
Total loss in iter18:  138.827529088
Total loss in iter19:  134.833240852
Total loss in iter20:  129.375457615
Total loss in it

# Logistic regression model to predict whether someone has coronary heart disease

In [122]:
data = pd.read_csv('heart.csv')

In [123]:
data.head()

sbp  tobacco   ldl  adiposity  famhist  typea  obesity  alcohol  age  chd
0  160    12.00  5.73      23.11  Present     49    25.30    97.20   52    1
1  144     0.01  4.41      28.61   Absent     55    28.87     2.06   63    1
2  118     0.08  3.48      32.28  Present     52    29.14     3.81   46    0
3  170     7.50  6.41      38.03  Present     51    31.99    24.26   58    1
4  134    13.60  3.50      27.78  Present     60    25.99    57.34   49    1

In [124]:
data.famhist[data['famhist']=='Present'] = 1
data.famhist[data['famhist']=='Absent'] = 0
data['chd_0'] = 0
data.chd_0[data['chd']==0] = 1.0
data.chd[data['chd']==1] = 1.0


/home/jesse/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/home/jesse/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/home/jesse/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/jesse/anaconda3/lib/python3.5/site-packages/ipykernel/__m

In [125]:
data.head()

sbp  tobacco   ldl  adiposity famhist  typea  obesity  alcohol  age  chd  \
0  160    12.00  5.73      23.11       1     49    25.30    97.20   52    1   
1  144     0.01  4.41      28.61       0     55    28.87     2.06   63    1   
2  118     0.08  3.48      32.28       1     52    29.14     3.81   46    0   
3  170     7.50  6.41      38.03       1     51    31.99    24.26   58    1   
4  134    13.60  3.50      27.78       1     60    25.99    57.34   49    1   

   chd_0  
0      0  
1      0  
2      1  
3      0  
4      0

In [126]:
Y = pd.concat([data.chd, data.chd_0], axis=1)
X = data.drop('chd', axis=1).drop('chd_0', axis=1)

In [127]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.13, random_state=0)

In [128]:
print("train data count: ", X_train.shape)
print("test data count: ", X_test.shape)

train data count:  (401, 9)
test data count:  (61, 9)


In [129]:
LEARNING_RATE = 1e-4
N_EPOCH = 100
BATCH_SIZE = 10

In [130]:
X = tf.placeholder(tf.float32, [BATCH_SIZE, 9])
Y = tf.placeholder(tf.float32, [BATCH_SIZE, 2])

In [131]:
W = tf.Variable(tf.zeros([9, 2]))
b = tf.Variable(tf.zeros([1, 2]))

In [132]:
y = tf.matmul(X, W) + b

In [133]:
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=y, labels=Y))
optimizer = tf.train.GradientDescentOptimizer(LEARNING_RATE).minimize(loss)

In [137]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./graphs', sess.graph)
    sess.run(init)
    n_batches = int(len(X_train)/BATCH_SIZE)
    for i in range(N_EPOCH):
        total_loss = 0.0
        for n in range(n_batches):
            X_batch = X_train[n*BATCH_SIZE:(n+1)*BATCH_SIZE]
            Y_batch = Y_train[n*BATCH_SIZE:(n+1)*BATCH_SIZE]
            _, loss_batch = sess.run([optimizer, loss], feed_dict={X:X_batch, Y:Y_batch})
            
            total_loss += loss_batch
        if i % 20 == 0:
            print("Average loss epoch {0}:{1}".format(i, total_loss/n_batches))
    
    n_batches = int(len(X_test) / BATCH_SIZE)
    total_correct_preds = 0
    for n in range(n_batches):
        X_batch = X_test[n*BATCH_SIZE:(n+1)*BATCH_SIZE]
        Y_batch = Y_test[n*BATCH_SIZE:(n+1)*BATCH_SIZE]
        _, loss_batch, logits_batch = sess.run([optimizer, loss, y], feed_dict={X: X_batch, Y: Y_batch})
        preds = tf.nn.softmax(logits_batch)

        correct_preds = tf.equal(tf.argmax(preds, 1), tf.argmax(Y_batch.as_matrix(), 1))
        accuracy = tf.reduce_sum(tf.cast(correct_preds, tf.float32))  # need numpy.count_nonzero(boolarr) :(
        total_correct_preds += sess.run(accuracy)
 
    print('Accuracy {0}%'.format(100 * total_correct_preds / (n_batches * BATCH_SIZE)))
    writer.close()

Average loss epoch 0:0.6856650069355965
Average loss epoch 20:0.6125385120511055
Average loss epoch 40:0.6023114033043384
Average loss epoch 60:0.5969743080437183
Average loss epoch 80:0.5937002699822187
Accuracy 66.66666666666667%


# Word2Vec

In [139]:
import time
import numpy as np
import tensorflow as tf
import collections
import random
import os
import math
import urllib
from urllib import request
import zipfile

In [140]:
def read_data(filename):
def build_vocab(words, vocab_size):
    """ Build vocabulary of VOCAB_SIZE most frequent words """
    dictionary = dict()
    count = [('UNK', -1)]
    count.extend(Counter(words).most_common(vocab_size - 1))

    # >> 原来的写法
    index = 0
    with open('processed/vocab_1000.tsv', "w") as f:
        # f.write("Name\n")
        for word, _ in count:
            dictionary[word] = index
            if index < 1000:
                f.write(word + "\n")
            index += 1
    index_dictionary = dict(zip(dictionary.values(), dictionary.keys()))
    with zipfile.ZipFile(filename) as f:
        data = tf.compat.as_str(f.read(f.namelist()[0])).split()
    return data

words = read_data('text8.zip')
print('data size', len(words))

data size 17005207


In [141]:
def build_vocab(words, vocab_size):
    """ Build vocabulary of VOCAB_SIZE most frequent words """
    dictionary = dict()
    count = [('UNK', -1)]
    count.extend(collection.Counter(words).most_common(vocab_size - 1))

    # >> 原来的写法
    index = 0
    with open('processed/vocab_1000.tsv', "w") as f:
        # f.write("Name\n")
        for word, _ in count:
            dictionary[word] = index
            if index < 1000:
                f.write(word + "\n")
            index += 1
    index_dictionary = dict(zip(dictionary.values(), dictionary.keys()))

In [ ]:
def convert_words_to_index(words, dictionary):